export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = "AUTH_LOGOUT"

export const PRODUCT_START = 'PRODUCT_START'
export const PRODUCT_LIST = 'PRODUCT_LIST'
export const PRODUCT_DELETE = 'PRODUCT_DELETE'
export const PRODUCT_DELETESTATUS = 'PRODUCT_DELETESTATUS'

export const PRODUCT_ADD = 'PRODUCT_ADD'
export const PRODUCT_SAVE = 'PRODUCT_SAVE'

